### PR TITLE
Linking project overview dashboard to README.md

### PR DESCRIPTION
**Pull request by alexkarezin**
# Description of change

Adding a shield to the header. Dashboard describes overall project structure and dependencies. Will be useful for new developers looking to contribute to the project.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Fix

## How the change has been tested

Link verified

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kwek20** [comment]
Hi @alexkarezin , I do not know why or what this pr should do. What is sourcespy? The link does not work either. Please explain why this needs to be added in a way that someone who doesnt know this can understand.

Thank you!

**Comment by alexkarezin** [comment]
The dashboard is helpful for developers looking to start contributing to the project. Link (https://sourcespy.com/github/iotaledgeriotajava) provides at-a-glance view of main elements including list of markdown documents, packages with model diagrams for each, graph of maven dependencies, network access points etc.

The link works well for me, let me know if it does not for you for some reason. Thank you for your time!

**Comment by kwek20** [comment]
It does not at all :(
https://downforeveryoneorjustme.com/sourcespy.com

Do i need a plugin or something?

**Comment by alexkarezin** [comment]
I believe the service is functional. No plugin is needed. The badge links to an overview of the project accumulating multiple project metrics and diagrams on one page and linked resources. Please check when you get a chance https://sourcespy.com/github/iotaledgeriotajava/ Thank you.

**Comment by alexkarezin** [comment]
This is only a documentation update. Can maybe @kwek20 merge it? Thank you!

**Comment by kwek20** [comment]
@alexkarezin The link now works for me, but we do have a certain cross library/repository guidelines to have them all display the same information.

@JakeSCahill What do you think about this?

**Comment by JakeSCahill** [comment]
It looks good to me @kwek20 😄 

We tend to have some standard badges and then project-specific ones.

**Pull request merged**
